---

ollama_port: 8080
ollama_version: "0.12.11"
ollama_install_vulkan: true
ollama_models:
  - name: TinyLlama
    url: "https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/\
      resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"
