---
- name: Converge
  hosts: all
  vars:
    litellm_port: 3000
    litellm_master_key: "sk-1234"
    litellm_models:
      - model_name: mock-llm
        litellm_params:
          model: openai/mock-llm
          api_base: http://localhost:8000/v1
          api_key: sk-1234
  roles:
    - role: litellm
